### ISSUE TITLE
Add missing page tests

### ISSUE THREAD

**Issue by keiranjprice101** [autoreduction/queue-processor#987]
Issue raised by: [developer/user/project requirement]

### What?
We need to add the missing tests for other pages. And as suggested ideally everyone should do some tests for at least one page.

The pages that need doing.
- [x] Run summary page
- [x] Rerun Page #1042
- [x] Job queue page #1042
- [x] Configure new runs page #1042
- [x] See instrument variables page #1042
- [x] Help Page 
- [ ] Graphs (maybe)

Tick off as we go.

### Where?
`webtests/`

**Comment by dtasev** [comment]
I'll do the rerun page as I'm having a look at it now for #1042, though I'll cover it as both view and selenium tests

**Comment by rickybassom** [comment]
I'll do the help page

**Comment by rickybassom** [comment]
I think we still need the Graphs tests
